# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20190728_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_id',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
