# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-03 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_users_salt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('access_token', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Users')),
            ],
            options={
                'db_table': 'token',
            },
        ),
    ]
